### PR TITLE
esp32/machine_pin: Add Pin.toggle() function.

### PR DESCRIPTION
**Pull request by rmokerone**
Very often, we need to flip the pin state, there is such a function that might be better.

### CODE REVIEW

**Comment by nickzoic** [comment]
Hi @rmokerone, I can see where you're coming from with this one and thanks for contributing, but I'm not sure it's a big win over doing it in Python with:

`pin.value(not pin.value())`

or just

`pin(not pin())`

... which is terser but I think a little less obvious.  They do the same thing under the hood.  Problem is, if we add Pin.toggle() to the ESP32 port we'll have to add it to all the others.  What do you think, @dpgeorge?

**Comment by rmokerone** [comment]
Thanks for your reply, I just want to try to submit the code, if you feel useless, please ignore.😁

**Comment by dpgeorge** [comment]
Yes I agree with @nickzoic : other ports don't have this so right now is not a good time to add it.

**Comment by nickzoic** [comment]
Thanks for your contribution, though, the code was good it just
wasn't quite aligned with the cross-port API (I've done a few of
those myself ...)


If there's something else which catches your eye please raise an issue
or a PR and we can discuss!


-----Nick





On Tue, Apr 4, 2017, at 20:18, rmokerone wrote:

> Closed #60[1].



> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
> 



--

Nick Moore <nick@zoic.org> 0409 656 267




Links:

  1. https://github.com/micropython/micropython-esp32/pull/60
  2. https://github.com/micropython/micropython-esp32/pull/60#event-1028118728

**Comment by pfalcon** [comment]
@nickzoic : Thanks for paying attention to "cross-port API". A lot of discussion (and pain) went into that already...

**Comment by rmokerone** [comment]
Can i ask what is our "cross-port API"? Maybe we need a standard:-D

**Comment by pfalcon** [comment]
@rmokerone : Sure, https://github.com/micropython/micropython/wiki/Hardware-API and discussion https://github.com/micropython/micropython/issues/1430 (325 messages over 1.5 years), should be a good read. (To be exact, some parts of those aren't up to date, the final standard is being recorded directly at the docs at http://docs.micropython.org/)

**Pull request closed without merging**
