### PR TITLE
NVS as config store

### PR DESCRIPTION
**Pull request by annejan**
Depends on https://github.com/SHA2017-badge/Firmware/pull/90

### CODE REVIEW

**Comment by annejan** [comment]
Sorry :( once again clicked on the wrong tree!!

**Comment by silbo** [comment]
what happened to this ? any updates on using NVS from micropython on esp32 ?

**Comment by MrSurly** [comment]
@silps I don't think there's a lot of interest, NVS is simply a partition type for the flash.  Since you have a file system available in MP, why not just write a JSON config there?

**Comment by silbo** [comment]
@MrSurly 👍 was just looking for the shortest effort in terms of writing code : )
JSON is the way to go yep, thanks!

**Pull request closed without merging**
